version: '3'
services:
  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=gopass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
volumes:
  mysql_data: